### ISSUE TITLE
There should be 2 branchs instead of 16

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#126]
Branch management is messy right now

- As long as we don't use extensive testing on pull requests through github actions, contributors should work on their own fork only
- Dependabot is imo useless except to spam irrelevant issues and PRs

**Comment by DeltaEvo** [comment]
> As long as we don't use extensive testing on pull requests through github actions, contributors should work on their own fork only

I disagree with that, using a fork makes things harder, for example to pull upstream you need to manager an extra remote, all contributors to this repo are not power user of git

I don't see the issues of having multiple branch :thinking:, the only one that matter is master all the other one are just WIP branches that are not ready for master

> Dependabot is imo useless except to spam irrelevant issues and PRs

It's not useless it help me too keep track of my upstream dependencies, some of them are noise (lilke some of the dev dependencies) but I need to configure dependabot for that, but for example update on minecraft-protocol and minecraft-data can bring useful update for us

**Comment by Sceat** [comment]
maybe for breaking changes but this is adding extra noise
![image](https://user-images.githubusercontent.com/11330271/107759871-3417e500-6d29-11eb-88c8-2638095ffbc7.png)
