### ISSUE TITLE
Show mob health value in it's nametag, next to his name and level

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#135]

**Comment by DeltaEvo** [comment]
Is this a duplicate of #104 ?

**Comment by Sceat** [comment]
nop, the name above the mob

**Comment by DeltaEvo** [comment]
This was not in the v1 do we really want to add that @Sceat ?

**Comment by Sceat** [comment]
It was a numeric value

**Comment by DeltaEvo** [comment]
It was for all the mobs ?

**Comment by Sceat** [comment]
![image](https://user-images.githubusercontent.com/11330271/109320288-23e72600-7850-11eb-8465-deff98b5c67f.png)

**Comment by Sceat** [comment]
We may had to attack them first to see the health
