### ISSUE TITLE
Show a msg when a player join for the first time

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#151]
![image](https://user-images.githubusercontent.com/11330271/109317874-7a9f3080-784d-11eb-9e36-637745970408.png)

**Comment by ToufouMaster** [comment]
it requires a database right?

**Comment by Sceat** [comment]
currently our database is just a state object in memory

**Comment by DeltaEvo** [comment]
For now we can just add a first_time in the state that is always true

**Comment by ToufouMaster** [comment]
k

**Comment by Sceat** [comment]
> it requires a database right?

supported in #262
