### ISSUE TITLE
Cancel Player Interactions with the World

### ISSUE THREAD

**Issue by DeltaEvo** [aresrpg/aresrpg#20]
We should cancel block breaking by either setting the player in adventure mode or by setting a packet to cancel the action

Currently the player is set to adventure mode but it still can interact with buttons or trapdors

**Comment by Sceat** [comment]
adventure mode is needed to be able to kill chickens in high grass imo

**Comment by Sceat** [comment]
- craft doesn't work
- opening inventories doesn't work
- doors are not a problem at the moment
- item frame doesn't seems to work

must just prevent putting flowers into pots and i think we're good

**Comment by Sceat** [comment]
additional infos on what adventure mode doesn't do https://bugs.mojang.com/browse/MC-109963
