### ISSUE TITLE
Enjin identities: Should we allow cross character wallets

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#258]
This is an interesting point, Enjin allows to have multiples identities per users which means multiple ETH address for a player.

With that in mind we can separate each character inventories for a single player, but should we do it ?

### Dofus
Creating a new class in dofus makes you start over with nothing, you still have your bank to keep items cross characters (we'd have a #50 problem)

### Terraria ?
A player always have the same inventory across all characters

**Comment by DeltaEvo** [comment]
# Final Fantasy

Your class depend on the weapon that you have in hand, if you switch the weapon, you switch your class (and keep your inventory)

**Comment by Sceat** [comment]
A character could be an actual NFT, so we could transfer character between wallets

**Comment by Sceat** [comment]
Enjin will be deprecated and replaced by solana SPL
