### ISSUE TITLE
Compact ChatComponents

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#260]
It's too boring to use the current `write_chat_msg` function as
```js
  write_chat_msg(
    { world },
    {
      message: JSON.stringify([
        { text: ' ' + sender.username, color: 'gray' },
        { text: " trouve qu'il y a trop de", color: 'yellow' },
        { text: ' fragile', color: 'blue', bold: 'true' },
        { text: ' ici', color: 'yellow' },
        { text: ' !', color: 'blue' },
      ]),
      client: sender,
    }
  )
```

We should be able to simply use
```js
  write_chat_msg({ 
	world,
	client: sender,
	message: ` &7${sender.username}&e trouve qu'il y a trop de &9fragile &eici &9!`
  })
```

> note that writing `&n &eHey` will write an underlined yellow ` Hey`

**Comment by Sceat** [comment]
there is also `hoverEVents` and `clickEvents` not to forget

**Comment by DeltaEvo** [comment]
I'm against using minecraft magic color codes

**Comment by ToufouMaster** [comment]
why?

**Comment by DeltaEvo** [comment]
We can implement this https://docs.adventure.kyori.net/minimessage.html#format but I don't think it will be a clear advantage over chat components

**Comment by Sceat** [comment]
that would make sense to keep the original verbose way but for long and complex texts.. lot of overhead if we don't have a simpler version to write stuff

**Comment by DeltaEvo** [comment]
> why?

Because the number is a magic value, it's unreadable

**Comment by ToufouMaster** [comment]
why not use "Something like {COLOR.RED} that?"

**Comment by DeltaEvo** [comment]
> that would make sense to keep the original verbose way but for long and complex texts.. lot of overhead if we don't have a simpler version to write stuff

A lot of these messages hardcoded in the code will disapear when we will implement #48

**Comment by Sceat** [comment]
> why not use "Something like {COLOR.RED} that?"

still quite verbose, the whole point would be to be super compact. That's magic numbers but also a well know feature which is part of the game like an easter egg

> A lot of these messages hardcoded in the code will disapear when we will implement #48
Another reason to be able to one-string the colors

**Comment by TheWolfOfDawn** [comment]
This is an option :
```JavaScript
const colors = [
  'black',
  'dark_blue',
  'dark_green',
  'dark_aqua',
  'dark_red',
  'dark_purple',
  'gold',
  'gray',
  'dark_gray',
  'blue',
  'green',
  'aqua',
  'red',
  'light_purple',
  'yellow',
  'white'
]

const style = {
  k:'obfuscated',
  l:'bold',
  m:'strikethrough',
  n:'underline',
  o:'italic',
  r:'reset',
  u:'normal'
}


const text_de_text = "§0uThis is normal black text and §9othis is italic blue text.§enThis is an underlined yellow text."

function parse_message(text) {
  let tmp = []
  let text_length = text.length

  let tmp_text = {text:''}
  let i = 0
  while(i<text_length) {
    if(text[i] == '§') {
      if(i != 0) {
        tmp.push(tmp_text)
      }

      tmp_text = {text:''}
      tmp_text.color = colors[parseInt(text[i+1], 16)]
      if(text[i+2] != 'u') {
        tmp_text[style[text[i+2]]] = true
      }

      i+=2
    }
    else {
      tmp_text.text += text[i]
    }

    i++
  }

  tmp.push(tmp_text)

  return JSON.stringify(tmp)
}

console.log(parse_message(text_de_text))
```

It return :
`[{"text":"This is normal black text and ","color":"black"},{"text":"this is italic blue text.","color":"blue","italic":true},{"text":"This is an underlined yellow text.","color":"yellow","underline":true}]`

**Comment by DeltaEvo** [comment]
> Another reason to be able to one-string the colors

No, it's a reason to not do this, because in the code we will only have translation keys and (maybe ?) use the crowdin system for colors :)

**Comment by Sceat** [comment]
Closing this issue because we can already send chat component with color codes
