### ISSUE TITLE
Experiment with negative font spacing

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#271]
That feature alone could make our entire GUI system without the needs for frame maps, there is many way to display custom chars
- boss bar
- action bar
- chat
- item names
- scoreboard
- achievements
- entity names
- player names (power title or aura, even alignment/guilde wings)

Useful links:
- [ttf fonts](https://www.reddit.com/r/Minecraft/comments/8yjroi/how_to_add_a_ttf_font_to_your_resource_pack/)
- [septicuss's guide](https://septicuss.notion.site/septicuss/Resource-Packs-cf80198cd49944128570b33d71053036)
- [Custom Inventory UI](https://www.spigotmc.org/threads/custom-inventory-ui.525744/)
- [Advanced resourcepack mechanics](https://www.spigotmc.org/threads/advanced-resourcepack-mechanics-how-to-create-custom-items-blocks-guis-and-more.520187/)
- [Left aligned action bars](https://www.spigotmc.org/threads/570389)
- [How to make custom tooltips](https://gist.github.com/Johnnnnnnny/3951396c13521563feaffddb8bded358)
- [Characters with special consideration](https://gist.github.com/tryashtar/6b2692e11ad46124e5129614fb7856a8) 
- [Custom Fonts in Minecraft](https://www.youtube.com/watch?v=-9bjbL1dYAE)
- [Make Custom UI Bars](https://www.youtube.com/watch?v=EL2X6ppZSCQ)
- [How To Customize FONTS In Minecraft](https://www.youtube.com/watch?v=-_HnXgiK_ps)

**Comment by DeltaEvo** [comment]
This will not replace maps on item frame because interaction is more limited

Some extra ressources on the topic
https://youtu.be/VYjrhEnmf9s
https://youtu.be/lZP-qnDFz5k
https://youtu.be/-9bjbL1dYAE

**Comment by Sceat** [comment]
in the second video he says that some kind of effect is more efficient to than armor stands 🤔

**Comment by ShiiroHikari** [comment]
Dungeon loot information

![Image](https://user-images.githubusercontent.com/21292913/221267003-f2f7f712-bdb4-46c2-a710-06c7b6f685a8.png)

Level up (maybe making something a little better looking would be more rewarding for the player...)

![Image](https://user-images.githubusercontent.com/21292913/221267152-6f885fc2-e7ce-49de-a5c7-02c561e1682b.png)

**Comment by ShiiroHikari** [comment]
Floor map selection 

![Image](https://user-images.githubusercontent.com/21292913/221284644-e8647ad5-275a-4fbe-8be8-568a6f37b3da.png)

**Comment by Sceat** [comment]
![image](https://user-images.githubusercontent.com/11330271/222170639-22fe6b12-6af4-4b84-8b94-67732a060925.png)

**Comment by ShiiroHikari** [comment]
i don't know if i like the last one. it looks great and certainly has a nice rpg-look to it, but some details just seem off. Like the inventory is too small and the fonts used are meh. Pretty much everything else is poggers

**Comment by ShiiroHikari** [comment]
> player names (power title or aura, even alignment/guilde wings)

confirmed dofus alignment system ?

**Comment by ShiiroHikari** [comment]
Having some custom epic contour around the title could be great as well. Could be another cosmetic addition : 
![image](https://user-images.githubusercontent.com/21292913/222177751-abcf4046-b82c-4854-af37-04ff594dc92c.png)

Also, Dofus-like auras ?
![image](https://user-images.githubusercontent.com/21292913/222178642-3a101f3b-ddf9-4668-8e2c-5e4e5b096a8d.png)
This one is maybe a bit hard to implement but the classic power aura is easier (hard to get a good image of it) :
![image](https://user-images.githubusercontent.com/21292913/222178896-7b961fc5-526f-4dd1-971e-89c31ec4d3a1.png)

**Comment by ShiiroHikari** [comment]
Directionnal arrow for quests : 
![Image](https://user-images.githubusercontent.com/21292913/222240329-c4e8870b-e03e-45a7-ba1a-52305b8ec768.png)



TP Menu (main menu and submenu) : 
this could be used for floor teleportation (main menu) then area teleportation (submenu) such as Floor 1 > Thebes
this could also be used for Instannce selection (main menu) then character selection (submenu, if you can have multiple characters on one instance)
![Image](https://user-images.githubusercontent.com/21292913/222240869-2624a6bc-c021-446f-8d8d-8baf24fb6ceb.png)
![Image](https://user-images.githubusercontent.com/21292913/222240911-69dd6d9c-48d2-440e-980e-19e6df368003.png)
![Image](https://user-images.githubusercontent.com/21292913/222240912-29c4dfad-a2b1-40e9-bb59-25dd43303051.png)



Custom NPC trades GUI : 
![Image](https://user-images.githubusercontent.com/21292913/222240993-ceafbbda-8139-4fb7-855e-91df80851e83.png)


AFK indication : 
![Image](https://user-images.githubusercontent.com/21292913/222241062-bcf88f7e-1672-41b3-90ee-2d9238c5e3ec.png)
