### ISSUE TITLE
Can we do something for the dependencies ?

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#299]
If there was only one PR with a summary of the dependencies to bump it would be okay, but having 10 PR from the bot it's really annoying

**Comment by DeltaEvo** [comment]
I don't see why does it bother you :thinking: ?
The only noise that is generated from that is on Discord

**Comment by DeltaEvo** [comment]
>  that's polluting the PR tab disappointed that's visually harder to follow what's being worked on

You can easily filter out theses PRs

It indeed generate more PRs that the contributors but I find it better to have only single updates, than to have a batched one, you can more easily identify what dependency update fails

For me the solution is just to do #282, but we need tests for that
