### ISSUE TITLE
Enforce generic colors

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#304]
We should add color constants in settings to be consistant across the server. Let's discuss and make a list

## Theme Flat

- BASE `#ECF0F1` | `italic`
- REWARD/SUCESS `#2ECC71` | `bold`
- WARN `#F1C40F` | `bold`
- INFO `#3498DB` | `bold`
- DANGER `#E74C3C` | `bold`
- CLICKABLE/HOVERABLE (item) `#9B59B6` | `underline` `?bold`
- CLICKABLE/HOVERABLE (entity/player) `#34495E` | `underline` `?bold`

![image](https://user-images.githubusercontent.com/11330271/132137163-8202efd3-135e-4d0a-bf95-bda6756b14ac.png)

**Comment by DeltaEvo** [comment]
Big :+1: for that

I don't know what to think of your theme, I think we should just try/implement it, it should be easily changeable in the future

Also for the theme I think we should also choose a font for it :)

**Comment by Sceat** [comment]
misswrote it's not metro it's actually flat, from https://materialui.co/flatuicolors
