### ISSUE TITLE
Fall damage applies in creative mode (or simply flying mode)

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#360]

**Comment by DeltaEvo** [comment]
I don't think this should be part of 1.0 milestone since the command to change gamemode is only a test command

**Comment by Sceat** [comment]
I'll let u judge by the impl but i'm slighty changing the way we handle damages so while we have a `flying` boolean in the context let's have that cuz it's annoying (we can deprecate the property later)

**Comment by Sceat** [comment]
actually i removed the `flying` property anyway we just need to know if he's creative for now

**Comment by Sceat** [comment]
just to avoid doing it again if we shall need it in the future, here's the snippet

*player/fly.js*
```js
import logger from '../logger.js'

const log = logger(import.meta)
const FLYING = 2

export default {
  /** @type {import('../context.js').Reducer} */
  reduce(state, { type, payload }) {
    if (type === 'packet/abilities') {
      // allowing the client to fly as he wants
      // but i guess we'll deleguate that to an anti cheat
      const { flags } = payload

      log.info({ payload }, 'fly my son')

      return {
        ...state,
        flying: flags === FLYING,
      }
    }
    return state
  },
}
```
