### ISSUE TITLE
Different glowing color for NFT loots

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#424]
When a mob die and drop an item, there is currently a white glow effect but we could change the color if the loot is an NFT.
We could also discuss to color it according to the item type or rarity

**Comment by ShiiroHikari** [comment]
would be possible to color it in regard to the item rarity and to make some particles around it or some slight beacon effect if it's NFT ; this way it can show both the NFT tag and the rarity tag

**Comment by Sceat** [comment]
for now we don't intend to implement ground items, nor a rarity system
