### ISSUE TITLE
Handle right click on a Bell

### ISSUE THREAD

**Issue by DeltaEvo** [aresrpg/aresrpg#443]
https://minecraft.fandom.com/wiki/Bell

- Play the bell sound
- Show the bell animation

**Comment by Sceat** [comment]
nice useless way to grow the amount of issues

![image](https://user-images.githubusercontent.com/11330271/150762966-0d418ea3-eddf-4104-9f06-d481b20f5ce4.png)

**Comment by DeltaEvo** [comment]
It's used on the new floor1 map
And is not part of the v1 milestone so :thinking:
