### ISSUE TITLE
Some trapdors should be openable

### ISSUE THREAD

**Issue by DeltaEvo** [aresrpg/aresrpg#444]
Implement openable trapdors

**Comment by Arkobalt** [comment]
Aren't trapdoors already openable ?

**Comment by Sceat** [comment]
It's client side only, and we may want to only allow certain trap doors and not all ? @DeltaEvo

**Comment by Sceat** [comment]
> Aren't trapdoors already openable ?

Probably client side trapdoors are enough, this issue isn't much detailed so let's close it for now
