### ISSUE TITLE
Allow multiple items & entities file sources

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#551]
Some proprietary data of aresrpg are going to be closed source, we need to allow `items.json` and `entities.json` to be loaded from multiple sources

We will have
- defaults files with a few items and entities in the repo
- production files with the rest of items and entities in a private package

**Comment by ToufouMaster** [comment]
can you explain more precisely how you want it to be done?

**Comment by Sceat** [comment]
working on this issue requires to setup a private package for the organization, or use a submodule like for the map, @DeltaEvo should confirm (i think submodule are a bit of a pain in the ass)
