### ISSUE TITLE
Player menu (book)

### ISSUE THREAD

**Issue by SohKey** [aresrpg/aresrpg#579]
Creates an interface for the player using the items frames to enable him to equip his stuff, to exchange with other players, or to choose his spells

<img src="https://media.discordapp.net/attachments/1045415479302434847/1054019294633140264/image.png">

related to #526

**Comment by Sceat** [comment]
Please improve the title and description of the issue

**Comment by Sceat** [comment]
Abandoned for impracticability of spawning those entities instead of a direct client GUI
