### ISSUE TITLE
Starter Quests: Barbarian

### ISSUE THREAD

**Issue by psychowolf960** [aresrpg/aresrpg#618]
_This is a draft for a quest for new players using the barbarian class._
**Player:** 
1. Greetings, barman. I am new in this town and have not yet met many of its inhabitants.
2. A fresh beer for me barman.

Barman: And greetings to you, barbarian. I am Roux le Maboul, ancient warrior of the clan of the Red Terror. It is a pleasure to meet another of our kind.

**Player:** 
1. The Red Terror? I have heard of them before but i can't remember where...
3. The Red terror? I know them! They were the strongest clan in the ancient times.
4. I got no time for this, goodbye.

**Barman:**
Ah, we are a fierce and proud clan. We were known for our prowess in battle and our skill in battle. But I digress. You look like warrior in need of job, and I have a task for you.

**Player:** 
1. What task is that?
2. No thanks.

**Barman:** 
Recently, a band of thieves have been plaguing the city. They have taken something very dear to me and I need a brave warrior to retrieve it. Will you take on this quest?

**Player:** 
1. Count on me. 
2. I can't help you at the time.
3. What is it that these thieves have taken from you?

**Barman**: 

2. They have stolen my ancient battle axe, passed down to me from my ancestors. It is not just a weapon, but a symbol of my clan and my heritage. I cannot let it fall into the hands of thieves.

**Player** : I understand. I will retrieve your axe and bring these thieves to justice.

### Quest accepted:
**Barman**: Good. The thieves are known to reside in the outskirts of the city. Be careful, they are cunning and dangerous. And remember, the axe is a sacred symbol of the Red Terror, it must be brought back to me. May the gods be with you on your quest.

### Quest denied:
May the god be with you adventurer!

**Comment by Sceat** [comment]
This should be in discussions or in the forum, not on issues. There is no quest system planned for now.
