### ISSUE TITLE
Timeframe of each hit by players

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg#632]
In vanilla minecraft, each mob will be invulnerable for a short period of time after each hit regardless of the source. After a discussion on discord we decided to implement a system per-player based.

When a player hit an entity (`use_entity`) we throttle the call and consider each loop a `hit_frame`.
For each `hit_frame` we prevent hitting twice the same entity. This is the most efficient and simple system to have a safe dps, This system has it flaws because if the frame is ending while the player just hit a new mob, he will be able to hit it again instantly. It may be hardly perceptible but it saves us the cost of storing a `last_hit` value for each player for each mob. 

It also allow us to modify the attack speed of players according to their [Haste](#640 )

**Comment by ShiiroHikari** [comment]
![image](https://user-images.githubusercontent.com/21292913/219716683-d5764b54-52fd-45e0-ba8c-90b40f762754.png)

**Comment by ShiiroHikari** [comment]
![image](https://user-images.githubusercontent.com/21292913/219718477-14d08ef1-f600-4c02-b0e6-e9cd6407056a.png)
