### ISSUE TITLE
Weapons and classes

### ISSUE THREAD

**Issue by ShiiroHikari** [aresrpg/aresrpg#646]
### Concerning class weapons, considering there are **4 classes** available. 
We could go for different models : 
1. `2` weapons specific per class, for a total of `8` types of weapons
2. `1` weapon specific per class and `1` weapon that is available for 2 classes (so `6` additional weapons), for a total of `10` types of weapons
3. `0` weapon specific and `1` weapon that is available for 2 classes (so `6` additional weapons), for a total of `6` types of weapons

Please add any other interesting model you can think of in the comments and i'll add them to the list.

> Also, please keep in mind that if, eventually, we want to add classes in the future, the easiest option by far is **1.**

### Concerning the weapons themselves and which class they could go with
Here is a non-exhaustive list of all the types of weapons we could use (considering option **2.**) : 

> As a reminder, the **4** classes currently available on AresRPG are : `Barbarian`, `Paladin`, `Archer` and `Mage`

- hammer (`Barbarian` exclusive)
- spear (`Paladin` exclusive)
- bow (`Archer` exclusive)
- staff (`Mage` exclusive)
- sword (`Barbarian` and `Paladin`)
- dagger (`Archer` and `Mage`)
- axe (`Barbarian` and `Archer`)
- ? (`Paladin` and `Mage`)
- ? (`Barbarian` and `Mage`)
- ? (`Paladin` and `Archer`)

Please add any other type of weapon you can think of in the comments and i'll add them to the list.

Also, please discuss the class assigned to each type in the comments as well.

**Comment by SohKey** [comment]
please move this [here](https://github.com/aresrpg/aresrpg/discussions/648)
