### ISSUE TITLE
Let the player know how hypothetically good his loot is

### ISSUE THREAD

**Issue by ShiiroHikari** [aresrpg/aresrpg#647]
Keeping aside the Rarity, there are lotss of methods that could **help** (not tell) the player know how good his loot is.

Let's consider a **Test weapon** that would give `10 to 20` Strength and `0 to 30` Vitality

If the player gets a weapon with `15` Strength and `20` Vitality, he has no idea of how good his **Test weapon** is since he doessn't have access to the min and max values. Therefore, if he wanted to sell it and there were not many similar items available, he wouldn't be able to guess a valid price.

If it says `15 Strength (10-20)` instead of `15 Strength` (which also could make the player think it's a flat stat), I think itt could help.

This doesn't seem very good looking though, so please discuss and give ideas to improve this in tthe comments.

**Comment by SohKey** [comment]
Maybe we can set a quality score on the weapons like it's done in **Lostark**
![image](https://user-images.githubusercontent.com/45180021/221961906-91a5c415-eb69-4bb9-aa6e-e55a34534cf6.png)

**Comment by ShiiroHikari** [comment]
> Perhaps a quality score could be assigned to the weapons, as in **Lostark** ![image](https://user-images.githubusercontent.com/45180021/221961906-91a5c415-eb69-4bb9-aa6e-e55a34534cf6.png)

This way it doesn't say which stats are good or aren't, just the overall quality of the weapon. It's more evasive and could help maintain some mystery around the stats while still letting the player know how valuable his loot is.
