### ISSUE TITLE
Add an utility function to create Entity Metadata

### ISSUE THREAD

**Issue by DeltaEvo** [aresrpg/aresrpg#88]
See the code and https://wiki.vg/Entity_metadata

**Comment by Sceat** [comment]
is this to allow custom states in entities ?

**Comment by Sceat** [comment]
@Sauronox working on it ?

**Comment by DeltaEvo** [comment]
> is this to allow custom states in entities ?

Not really it's to refactor the ugly code that use metadata https://github.com/aresrpg/aresrpg/blob/master/src/mobs/position.js#L52-68
